#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ""
echo -e "\033[1;33mRunning pre-commit tests..\033[0m"
echo ""

# Run commitlint

# Check the exit status of commitlint
if npx commitlint --edit ; then
  echo ""
  echo -e "\033[0;32m✅✅ All files are good to push...\033[0m"
  echo ""
  exit 0
else
  echo ""
  echo -e "\033[0;31m😱😱 There is some typo in commit message as above... 😱😱\033[0m"
  echo ""
  exit 1
fi
