#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ""
echo -e "\033[1;33mRunning pre-commit tests..\033[0m"
echo ""
npx --no -- commitlint --edit 
echo ""
echo ""
echo -e "\033[1;33mAll files are good to push\033[0m"
echo ""